language: python
branches:
  only:
  - source
python:
- 2.7
install:
- pip install -r requirements.txt
- git clone https://github.com/studenton/Flex themes/Flex
- git clone https://github.com/getpelican/pelican-plugins
script:
- fab publish:"Build site"
