language: python
branches:
  only:
  - source
python:
- 2.7
install:
- pip install -r requirements.txt
- git clone -b themes/Flex https://github.com/studenton/Flex
- git clone https://github.com/getpelican/pelican-plugins
script:
- fab publish:"Build site"
env:
  global:
    secure: k0hgNvoRHcbpsRpnjo9V2qFSuyjhNLWNJzbIvaYKKlCZSPiVm9uYEU9RZXGY8MJ9ZSDKJ9OGn32ei/1riuBB7CZr73m0B1Yj9M2SFDwTextLbIOp5D3+9R8g2TnWRjggZrHl5D9DMRtE82tpy7yKiGwLMvXCPGsagUvtNEB/vL5NrfNuRWyZQxDMw8B2xzMWirNiPNwxdFaTzaX/VA8vuuQkTiKGg1N02NCl4O5J+yDRIyifgV3HTv2KZ00Hh7NWAP1drKAS2LtCHpGje5GwIKN7HfUEWlljLJmpajSpOqMttS9DaMKhxy/wwbn1Ti6ZV5d9TNBkFUITEy753QtInWWmvsqY9BAgwp6OSDToEp3Oj75SCrUCpKjxM41Io+n9pCjmUg0YOGMeeKR8XQZugZ9LQZb7cc2XDDKtHFvqJ4E/7SpwPfKNPmSgTzvjDq9n6TfwU6tdesz/TVg//xMZh9r1VWm6gFYsxG4KXWoy3oPRMNoX4x1bsS0NRkU2PkqG6+ZHQZcFX/9oadhFVgwfsNuR6qldCIzsH47kReoVaQhTA+lCe3D8era2sIsPnll7pzGxe2IyU660ZkA+wwc5VGZup6PWD8dHCbkR0P9tn1wWSXqbRKQMxEm0+Z09C7T6mL7otvBv62UUnjpDoGltBvWIZl5XeYeNTlzPIR+N+E0=
