language: python
cache: pip
branches:
  only:
  - source
python:
- 3.5
install:
- gem install sass
- pip install -r requirements.txt
- git config --global user.email "meamitkc@gmail.com"
- git config --global user.name "Amit Chaudhary"
- git clone https://github.com/amitness/pneumatic themes/pneumatic
- git clone https://github.com/getpelican/pelican-plugins
script:
- fab publish:"Build site"
