language: python
cache: pip
branches:
  only:
  - source
python:
- 2.7
install:
- pip install -r requirements.txt
- git config --global user.email "meamitkc@gmail.com"
- git config --global user.name "Amit Chaudhary"
- git clone https://github.com/amitness/Flex themes/Flex
- git clone https://github.com/getpelican/pelican-plugins
script:
- fab publish:"Build site"
